import { OrderFormI } from "../../types/order";

export const initialOrderForm: OrderFormI = {
    orderDate: new Date().toISOString().split("T")[0],
    currency: "",
    currencyValue: "",
    currencyLabel: "",
    paymentMethodValue: "",
    paymentMethodLabel: "",
    paymentMethod: "",
    requestingAreaLabel: "",
    requestingAreaValue: "",
    costCenterValue: "",
    costCenterLabel: "",
    isAffectedIGV: false,
    isAffectedIGVLabel: "",
    taxLabel: "0",
    retentionLabel: "",
    perceptionLabel: "",
    detractionLabel: "",
    taxValue: "",
    retentionValue:"",
    perceptionValue: "",
    detractionValue: "",
    totalLabel: "",
    tax: 0,
    retention: 0,
    perception: 0,
    detraction: 0,
    total: 0,
    approverLabel: "",
    approverValue: "",
    automaticSignature: false,
    providerRuc: "",
    providerDescription: "",
    providerAddress: "",
    providerAccountNumber: "",
    providerAccountCCI: "",
    providerAccountBank: "",
    observations: "",
    approvingStaffId: "",
    companyId: "",
    correlative: "",
    costCenterId: "",
    orderTypeId: "",
    period: "",
    requestingAreaId: "",
    subtotal: 0,
    systemUser: "",
    taxRetentionLabel: "",
    details: [
        {
             product: "",
             quantity: 0,
             subtotal: 0,
             unitPrice: 0,
             measurement: ""
        }
    ]
}