import { DocumentFormI, OrderLSI } from "../../types/order-document";

export const initialDocumentForm: DocumentFormI = {
    documentTypeLabel: "",
    documentTypeValue: "",
    issueTypeLabel: "",
    issueTypeValue: "",
    receiptDate: new Date(),
    issueDate: new Date(),
    dueDate: new Date(),
    exchangeRate: 0,
    annotation: "",
    code: "",
    perceptionPercLabel: "",
    detractionPercLabel: "",
    perceptionPercValue: "",
    detractionPercValue: "",
    biorgeya: "",
    orderDocumentNumber: "",
    subtotal: "",
    perceptionCalcValue: "",
    detractionCalcValue: "",
    fise: "",
    otherPayments: "",
    isPettyCash: false,
    isAffectedTaxRetention: true,
    taxRetentionValue: "",
    retentionLabel: "",
    taxLabel: "",
    taxValue: "",
    retentionValue: "",
    total: "",
    perceptionDetractionValue: "",
}

export const initialOrderLSI: OrderLSI = {
    companyId: "",
    orderTypeId: "",
    period: "",
    correlative: "",
    currency: "",
    total: 0,
    tax: null,
    perception: null,
    detraction: null,
    retention: null,
}